spring.application.name=automasterbaratieri
spring.profiles.active=test

# Fuso horário do Brasil
spring.jackson.time-zone=America/Sao_Paulo

# Carrega o seu ficheiro email.properties (se existir) sem dar erro
spring.config.import=optional:classpath:email.properties

# URL base da aplicação para links em e-mails e PDFs
app.base-url=http://localhost:8080
