
spring.datasource.url=jdbc:postgresql://localhost:5432/automaster_db
spring.datasource.username=automaster_admin
spring.datasource.password=admin_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Mostra o SQL no terminal para ajudar a debugar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.auto-commit=true
# Mude de 'update' para 'create' para FORÇAR a criação agora
spring.jpa.hibernate.ddl-auto=create

# Garanta que estas linhas abaixo estejam exatamente assim
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always