
spring.datasource.url=jdbc:postgresql://localhost:5432/automaster_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# O Hibernate irá apenas validar o schema do banco (sem atualizações automáticas)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL no terminal (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true