spring.application.name=automasterbaratieri
spring.profiles.active=dev

# Fuso horário do Brasil
spring.jackson.time-zone=America/Sao_Paulo

# Carrega o seu ficheiro email.properties (se existir) sem dar erro
spring.config.import=optional:classpath:email.properties