# Configurações do email.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tiagobaratieri97@gmail.com
spring.mail.password=mutqpbcxfclokyoc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


automaster.notificacao.estoque.remetente=tiagobaratieri97@gmail.com
automaster.notificacao.estoque.destinatario=tiagobaratieri97@gmail.com